apiVersion: v1
kind: ConfigMap
metadata:
  name: chaos-monkey-config
  namespace: petclinic-c1
data:
  application.properties: |
    # Chaos Monkey Configuration
    chaos.monkey.enabled=true
    chaos.monkey.watcher.enabled=true
    chaos.monkey.assaults.enabled=true
    
    # Latency Attack Configuration
    chaos.monkey.assaults.latency.active=true
    chaos.monkey.assaults.latency.latency-range-start=1000
    chaos.monkey.assaults.latency.latency-range-end=3000
    
    # Exception Attack Configuration
    chaos.monkey.assaults.exceptions.active=false
    chaos.monkey.assaults.exceptions.level=3
    
    # Memory Attack Configuration
    chaos.monkey.assaults.memory.active=false
    chaos.monkey.assaults.memory.memory-fill-mb=100
    
    # Application Kill Attack Configuration
    chaos.monkey.assaults.kill-application.active=false
    
    # Watcher Configuration
    chaos.monkey.watcher.controller=true
    chaos.monkey.watcher.rest-controller=true
    chaos.monkey.watcher.service=true
    chaos.monkey.watcher.repository=true
    chaos.monkey.watcher.component=true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chaos-monkey-config
  namespace: petclinic-c2
data:
  application.properties: |
    # Chaos Monkey Configuration
    chaos.monkey.enabled=true
    chaos.monkey.watcher.enabled=true
    chaos.monkey.assaults.enabled=true
    
    # Latency Attack Configuration
    chaos.monkey.assaults.latency.active=false
    chaos.monkey.assaults.latency.latency-range-start=1000
    chaos.monkey.assaults.latency.latency-range-end=3000
    
    # Exception Attack Configuration
    chaos.monkey.assaults.exceptions.active=true
    chaos.monkey.assaults.exceptions.level=3
    
    # Memory Attack Configuration
    chaos.monkey.assaults.memory.active=false
    chaos.monkey.assaults.memory.memory-fill-mb=100
    
    # Application Kill Attack Configuration
    chaos.monkey.assaults.kill-application.active=false
    
    # Watcher Configuration
    chaos.monkey.watcher.controller=true
    chaos.monkey.watcher.rest-controller=true
    chaos.monkey.watcher.service=true
    chaos.monkey.watcher.repository=true
    chaos.monkey.watcher.component=true
